#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -z "$NODE_PATH" ]; then
  export NODE_PATH="/mnt/g/vue3_admin_code/vue3_admin_code/node_modules/js-beautify/js/bin/node_modules:/mnt/g/vue3_admin_code/vue3_admin_code/node_modules/js-beautify/js/node_modules:/mnt/g/vue3_admin_code/vue3_admin_code/node_modules/js-beautify/node_modules:/mnt/g/vue3_admin_code/vue3_admin_code/node_modules:/mnt/g/vue3_admin_code/node_modules:/mnt/g/node_modules:/mnt/g/vue3_admin_code/vue3_admin_code/node_modules/.pnpm/node_modules"
else
  export NODE_PATH="/mnt/g/vue3_admin_code/vue3_admin_code/node_modules/js-beautify/js/bin/node_modules:/mnt/g/vue3_admin_code/vue3_admin_code/node_modules/js-beautify/js/node_modules:/mnt/g/vue3_admin_code/vue3_admin_code/node_modules/js-beautify/node_modules:/mnt/g/vue3_admin_code/vue3_admin_code/node_modules:/mnt/g/vue3_admin_code/node_modules:/mnt/g/node_modules:/mnt/g/vue3_admin_code/vue3_admin_code/node_modules/.pnpm/node_modules:$NODE_PATH"
fi
if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../js-beautify/js/bin/html-beautify.js" "$@"
else
  exec node  "$basedir/../js-beautify/js/bin/html-beautify.js" "$@"
fi
