#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -z "$NODE_PATH" ]; then
  export NODE_PATH="/mnt/g/vue3_admin_code/vue3_admin_code/node_modules/.pnpm/vitest@1.4.0_@types+node@20.12.6_jsdom@24.0.0_less@4.2.0/node_modules/vitest/node_modules:/mnt/g/vue3_admin_code/vue3_admin_code/node_modules/.pnpm/vitest@1.4.0_@types+node@20.12.6_jsdom@24.0.0_less@4.2.0/node_modules:/mnt/g/vue3_admin_code/vue3_admin_code/node_modules/.pnpm/node_modules"
else
  export NODE_PATH="/mnt/g/vue3_admin_code/vue3_admin_code/node_modules/.pnpm/vitest@1.4.0_@types+node@20.12.6_jsdom@24.0.0_less@4.2.0/node_modules/vitest/node_modules:/mnt/g/vue3_admin_code/vue3_admin_code/node_modules/.pnpm/vitest@1.4.0_@types+node@20.12.6_jsdom@24.0.0_less@4.2.0/node_modules:/mnt/g/vue3_admin_code/vue3_admin_code/node_modules/.pnpm/node_modules:$NODE_PATH"
fi
if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../vitest/vitest.mjs" "$@"
else
  exec node  "$basedir/../vitest/vitest.mjs" "$@"
fi
